### ISSUE TITLE
Question on categories for cohort.config file

### ISSUE THREAD

**Issue by Ysuita** [Sydney-Informatics-Hub/Fastq-to-BAM#14]
Hello there,

I'm trying to use your package to publicly available RNA seq fastq data that I got from NCBI website, which header contains only SRR code (see the attached photo) and doesn't sample ID/Lab Sample ID/Seq_centre. Could I still apply this package to these data? If so, what would I do to make it work? Thank you very much for reading my inquiry. I would greatly appreciate your help! 

![image](https://user-images.githubusercontent.com/46567752/148012341-b4510a2e-e40d-4d33-abad-380acacbc6fa.png)

**Comment by georgiesamaha** [comment]
Hi Ysuita, 

Apologies for the delay in responding to you. 

We recommend you try our RNASeqDE pipeline for aligning your RNA data (https://github.com/Sydney-Informatics-Hub/RNASeq-DE). This pipeline is more appropriate for your data as it uses STAR instead of BWA to align reads to a reference genome, which is splice aware. Our RNASeqDE pipeline is also written for NCI Gadi and still a work in progress, so if you have any problems, log an issue and we'll be able to help you out :) 

Good luck!
